version: '3.7'

services:
  feedapp:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_NEO4J_URI=bolt://neo4j:7687
      - SPRING_NEO4J_USERNAME=neo4j
      - SPRING_NEO4J_PASSWORD=password
    depends_on:
      - frontend
      - rabbitmq
      - neo4j

  # frontend
  frontend:
    build: frontend/.
    ports:
      - "5173:5173"
  # RabbitMQ
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # Neo4j
  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"